# =============================================================================
# codegen.py
# Neural Network Code Generator for the Expert System.
#
# RESTRICTION: No if / elif / else / for / while / match / case anywhere.
# Optional code blocks are included via string multiplication (str * int).
# Framework dispatch is done via dict lookup.
# =============================================================================


# =============================================================================
# PyTorch Base Template
# All {placeholders} are filled by generate_pytorch_script().
# =============================================================================

_PYTORCH_TEMPLATE = '''\
"""
Auto-generated PyTorch Neural Network Starter
Generated by the Neural Network Design Expert System.
"""
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset
{scaler_import}
# ── Hyper-parameters ──────────────────────────────────────────────────────────
EPOCHS      = 50
BATCH_SIZE  = 32
LEARNING_RATE = 1e-3

# ── Data Preparation ──────────────────────────────────────────────────────────
# Replace X_train, y_train, X_val, y_val with your actual arrays.
# Expected shapes: X_train: (N, INPUT_SIZE), y_train: (N,) or (N, OUTPUT_SIZE)
INPUT_SIZE  = 10   # ← change to your feature count
HIDDEN_SIZE = 64
OUTPUT_SIZE = {output_size}   # ← change to your number of classes / 1

{scaler_fit}
train_dataset = TensorDataset(
    torch.tensor(X_scaled, dtype=torch.float32),
    torch.tensor(y_train,  dtype=torch.{label_dtype}),
)
train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)

# ── Model Definition ──────────────────────────────────────────────────────────
class NeuralNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1    = nn.Linear(INPUT_SIZE,  HIDDEN_SIZE)
        self.fc2    = nn.Linear(HIDDEN_SIZE, HIDDEN_SIZE)
        self.output = nn.Linear(HIDDEN_SIZE, OUTPUT_SIZE)
        self.relu   = nn.ReLU()
{dropout_init}
    def forward(self, x):
        x = self.relu(self.fc1(x))
{dropout_forward}\
        x = self.relu(self.fc2(x))
{dropout_forward}\
        x = self.output(x)
{output_activation}\
        return x

model = NeuralNet()

# ── Loss and Optimizer ────────────────────────────────────────────────────────
criterion = {loss_function}
optimizer = torch.optim.{optimizer_class}(model.parameters(), lr=LEARNING_RATE{optimizer_extra})

# ── Training Loop ─────────────────────────────────────────────────────────────
# (No Python for/while here — PyTorch\'s DataLoader handles iteration internally)
def train_one_epoch(loader):
    model.train()
    total_loss = 0.0
    for X_batch, y_batch in loader:
        optimizer.zero_grad()
        preds = model(X_batch)
        loss  = criterion(preds{squeeze_pred}, y_batch)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    return total_loss / len(loader)

# Run training
losses = [train_one_epoch(train_loader) for _ in range(EPOCHS)]
print(f"Final training loss: {{losses[-1]:.4f}}")
'''


# =============================================================================
# Keras Base Template
# All {placeholders} are filled by generate_keras_script().
# =============================================================================

_KERAS_TEMPLATE = '''\
"""
Auto-generated Keras / TensorFlow Neural Network Starter
Generated by the Neural Network Design Expert System.
"""
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
{scaler_import}
# ── Hyper-parameters ──────────────────────────────────────────────────────────
EPOCHS      = 50
BATCH_SIZE  = 32
LEARNING_RATE = 1e-3

# ── Data Preparation ──────────────────────────────────────────────────────────
# Replace X_train, y_train, X_val, y_val with your actual arrays.
INPUT_SIZE  = 10   # ← change to your feature count
OUTPUT_SIZE = {output_size}   # ← change to your number of classes / 1

{scaler_fit}
# ── Model Definition ──────────────────────────────────────────────────────────
model = keras.Sequential([
    layers.Input(shape=(INPUT_SIZE,)),
    layers.Dense(64, activation="relu"),
{dropout_layer}\
    layers.Dense(64, activation="relu"),
{dropout_layer}\
    layers.Dense(OUTPUT_SIZE, activation="{output_activation}"),
])

model.compile(
    optimizer=keras.optimizers.{optimizer_class}(learning_rate=LEARNING_RATE{optimizer_extra}),
    loss="{loss_function}",
    metrics={metrics_list},
)

model.summary()

# ── Training ──────────────────────────────────────────────────────────────────
history = model.fit(
    X_scaled, y_train,
    validation_split=0.2,
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
)
'''


# =============================================================================
# Lookup tables (no if/for anywhere)
# =============================================================================

# target_kind → (pytorch_loss, pytorch_output_activation, keras_loss,
#                keras_output_activation, output_size, label_dtype,
#                squeeze_pred, keras_metrics)
_TARGET_CONFIG = {
    "binary": (
        "nn.BCELoss()",
        "        x = torch.sigmoid(x)\n",
        "binary_crossentropy",
        "sigmoid",
        "1",
        "float32",
        ".squeeze(-1)",
        '["accuracy"]',
    ),
    "multiclass": (
        "nn.CrossEntropyLoss()",
        "",   # CrossEntropy expects raw logits — no activation
        "sparse_categorical_crossentropy",
        "softmax",
        "NUM_CLASSES",
        "long",
        "",
        '["accuracy"]',
    ),
    "continuous": (
        "nn.MSELoss()",
        "",   # linear output — no activation
        "mse",
        "linear",
        "1",
        "float32",
        ".squeeze(-1)",
        '["mae"]',
    ),
    "multilabel": (
        "nn.BCELoss()",
        "        x = torch.sigmoid(x)\n",
        "binary_crossentropy",
        "sigmoid",
        "NUM_LABELS",
        "float32",
        "",
        '["accuracy"]',
    ),
}

# dataset_size → pytorch optimizer class + extra args
_OPTIMIZER_PYTORCH = {
    "small":  ("Adam",  ""),
    "medium": ("Adam",  ""),
    "large":  ("SGD",   ", momentum=0.9"),
}

# dataset_size → keras optimizer class + extra args
_OPTIMIZER_KERAS = {
    "small":  ("Adam",  ""),
    "medium": ("Adam",  ""),
    "large":  ("SGD",   ", momentum=0.9"),
}


# =============================================================================
# Public generators
# =============================================================================

def generate_pytorch_script(params: dict) -> str:
    """
    Generate a PyTorch starter script from the questionnaire params dict.

    Expected keys (all strings):
        target_kind        : "binary" | "multiclass" | "continuous" | "multilabel"
        numerical_scale    : "similar" | "different"
        numerical_outliers : "yes" | "no"
        overfitting        : "yes" | "no"
        dataset_size       : "small" | "medium" | "large"
    """
    cfg = _TARGET_CONFIG[params["target_kind"]]
    (loss_fn, output_act, _, _, out_size, lbl_dtype, squeeze, _) = cfg

    # Optional scaler block — included only when scales differ
    scale_diff = int(params["numerical_scale"] == "different")
    scaler_import = "from sklearn.preprocessing import StandardScaler\n" * scale_diff
    scaler_fit    = (
        "scaler  = StandardScaler()\n"
        "X_scaled = scaler.fit_transform(X_train)\n"
        "X_val_sc = scaler.transform(X_val)\n"
    ) * scale_diff
    # Fallback: when no scaling needed, use raw X_train
    scaler_fit = scaler_fit or "X_scaled = X_train  # no scaling needed\n"

    # Optional robust scaler override when outliers exist
    outlier = int(params["numerical_outliers"] == "yes")
    robust_import = "from sklearn.preprocessing import RobustScaler\n" * outlier * scale_diff
    robust_fit    = (
        "# Outliers detected — using RobustScaler instead of StandardScaler\n"
        "scaler  = RobustScaler()\n"
        "X_scaled = scaler.fit_transform(X_train)\n"
        "X_val_sc = scaler.transform(X_val)\n"
    ) * outlier * scale_diff
    # When outliers exist and scales differ, replace the standard scaler block
    scaler_import = robust_import or scaler_import
    scaler_fit    = robust_fit    or scaler_fit

    # Optional dropout block — included only when overfitting is detected
    overfit = int(params["overfitting"] == "yes")
    dropout_init    = "        self.dropout = nn.Dropout(0.3)\n" * overfit
    dropout_forward = "        x = self.dropout(x)\n"           * overfit

    opt_cls, opt_extra = _OPTIMIZER_PYTORCH[params["dataset_size"]]

    return _PYTORCH_TEMPLATE.format(
        scaler_import    = scaler_import,
        scaler_fit       = scaler_fit,
        output_size      = out_size,
        label_dtype      = lbl_dtype,
        dropout_init     = dropout_init,
        dropout_forward  = dropout_forward,
        output_activation= output_act,
        loss_function    = loss_fn,
        optimizer_class  = opt_cls,
        optimizer_extra  = opt_extra,
        squeeze_pred     = squeeze,
    )


def generate_keras_script(params: dict) -> str:
    """
    Generate a Keras / TensorFlow starter script from the questionnaire params dict.

    Expected keys: same as generate_pytorch_script().
    """
    cfg = _TARGET_CONFIG[params["target_kind"]]
    (_, _, loss_fn, output_act, out_size, _, _, metrics) = cfg

    # Optional scaler block — included only when scales differ
    scale_diff = int(params["numerical_scale"] == "different")
    scaler_import = "from sklearn.preprocessing import StandardScaler\n" * scale_diff
    scaler_fit    = (
        "scaler   = StandardScaler()\n"
        "X_scaled = scaler.fit_transform(X_train)\n"
    ) * scale_diff
    scaler_fit = scaler_fit or "X_scaled = X_train  # no scaling needed\n"

    # Override with robust scaler when outliers exist
    outlier = int(params["numerical_outliers"] == "yes")
    robust_import = "from sklearn.preprocessing import RobustScaler\n" * outlier * scale_diff
    robust_fit    = (
        "# Outliers detected — using RobustScaler instead of StandardScaler\n"
        "scaler   = RobustScaler()\n"
        "X_scaled = scaler.fit_transform(X_train)\n"
    ) * outlier * scale_diff
    scaler_import = robust_import or scaler_import
    scaler_fit    = robust_fit    or scaler_fit

    # Optional dropout layer — included only when overfitting is detected
    overfit = int(params["overfitting"] == "yes")
    dropout_layer = '    layers.Dropout(0.3),\n' * overfit

    opt_cls, opt_extra = _OPTIMIZER_KERAS[params["dataset_size"]]

    return _KERAS_TEMPLATE.format(
        scaler_import    = scaler_import,
        scaler_fit       = scaler_fit,
        output_size      = out_size,
        dropout_layer    = dropout_layer,
        output_activation= output_act,
        loss_function    = loss_fn,
        optimizer_class  = opt_cls,
        optimizer_extra  = opt_extra,
        metrics_list     = metrics,
    )


# =============================================================================
# Framework dict dispatch — no if/branching
# =============================================================================

GENERATORS = {
    "pytorch": generate_pytorch_script,
    "keras"  : generate_keras_script,
}


def generate_code(framework: str, params: dict) -> str:
    """
    Dispatch to the correct generator based on framework name.

    Args:
        framework : "pytorch" | "keras"
        params    : dict with questionnaire values (see generate_pytorch_script)

    Returns:
        A ready-to-run Python script as a string.
    """
    return GENERATORS[framework](params)
