# =============================================================================
# codegen.py
# Neural Network Code Generator for the Expert System.
# =============================================================================

from experta import KnowledgeEngine, Rule, AND
from facts import FrameworkFact, ProblemFact, DatasetFact, FeatureFact, TrainingFact


# =============================================================================
# PyTorch Base Template
# All {placeholders} are filled by generate_pytorch_script().
# =============================================================================

_PYTORCH_TEMPLATE = '''\
"""
Auto-generated PyTorch Neural Network Starter
Generated by the Neural Network Design Expert System.
"""
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset
{scaler_import}
# ── Hyper-parameters ──────────────────────────────────────────────────────────
EPOCHS      = 50
BATCH_SIZE  = 32
LEARNING_RATE = 1e-3

# ── Data Preparation ──────────────────────────────────────────────────────────
# Replace X_train, y_train, X_val, y_val with your actual arrays.
# Expected shapes: X_train: (N, INPUT_SIZE), y_train: (N,) or (N, OUTPUT_SIZE)
INPUT_SIZE  = 10   # ← change to your feature count
HIDDEN_SIZE = 64
OUTPUT_SIZE = {output_size}   # ← change to your number of classes / 1

{scaler_fit}
train_dataset = TensorDataset(
    torch.tensor(X_scaled, dtype=torch.float32),
    torch.tensor(y_train,  dtype=torch.{label_dtype}),
)
train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)

# ── Model Definition ──────────────────────────────────────────────────────────
class NeuralNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1    = nn.Linear(INPUT_SIZE,  HIDDEN_SIZE)
        self.fc2    = nn.Linear(HIDDEN_SIZE, HIDDEN_SIZE)
        self.output = nn.Linear(HIDDEN_SIZE, OUTPUT_SIZE)
        self.relu   = nn.ReLU()
{dropout_init}
    def forward(self, x):
        x = self.relu(self.fc1(x))
{dropout_forward}\
        x = self.relu(self.fc2(x))
{dropout_forward}\
        x = self.output(x)
{output_activation}\
        return x

model = NeuralNet()

# ── Loss and Optimizer ────────────────────────────────────────────────────────
criterion = {loss_function}
optimizer = torch.optim.{optimizer_class}(model.parameters(), lr=LEARNING_RATE{optimizer_extra})

# ── Training Loop ─────────────────────────────────────────────────────────────
# (No Python for/while here — PyTorch\'s DataLoader handles iteration internally)
def train_one_epoch(loader):
    model.train()
    total_loss = 0.0
    for X_batch, y_batch in loader:
        optimizer.zero_grad()
        preds = model(X_batch)
        loss  = criterion(preds{squeeze_pred}, y_batch)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    return total_loss / len(loader)

# Run training
losses = [train_one_epoch(train_loader) for _ in range(EPOCHS)]
print(f"Final training loss: {{losses[-1]:.4f}}")
'''


# =============================================================================
# Keras Base Template
# All {placeholders} are filled by generate_keras_script().
# =============================================================================

_KERAS_TEMPLATE = '''\
"""
Auto-generated Keras / TensorFlow Neural Network Starter
Generated by the Neural Network Design Expert System.
"""
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
{scaler_import}
# ── Hyper-parameters ──────────────────────────────────────────────────────────
EPOCHS      = 50
BATCH_SIZE  = 32
LEARNING_RATE = 1e-3

# ── Data Preparation ──────────────────────────────────────────────────────────
# Replace X_train, y_train, X_val, y_val with your actual arrays.
INPUT_SIZE  = 10   # ← change to your feature count
OUTPUT_SIZE = {output_size}   # ← change to your number of classes / 1

{scaler_fit}
# ── Model Definition ──────────────────────────────────────────────────────────
model = keras.Sequential([
    layers.Input(shape=(INPUT_SIZE,)),
    layers.Dense(64, activation="relu"),
{dropout_layer}\
    layers.Dense(64, activation="relu"),
{dropout_layer}\
    layers.Dense(OUTPUT_SIZE, activation="{output_activation}"),
])

model.compile(
    optimizer=keras.optimizers.{optimizer_class}(learning_rate=LEARNING_RATE{optimizer_extra}),
    loss="{loss_function}",
    metrics={metrics_list},
)

model.summary()

# ── Training ──────────────────────────────────────────────────────────────────
history = model.fit(
    X_scaled, y_train,
    validation_split=0.2,
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
)
'''


# =============================================================================
# Code Builder & Experta Engine
# =============================================================================

class CodeBuilder:
    def __init__(self):
        # Default scaling: none
        self.scaler_import = ""
        self.scaler_fit = "X_scaled = X_train  # no scaling needed\n"
        
        # Output layers / targets
        self.output_size = "1"
        self.label_dtype = "float32"
        self.output_activation = ""
        self.loss_function = "nn.MSELoss()"
        self.squeeze_pred = ""
        self.metrics_list = '["mae"]'
        
        # Optimizer defaults
        self.optimizer_class = "Adam"
        self.optimizer_extra = ""
        
        # Dropout / regularization defaults
        self.dropout_init = ""
        self.dropout_forward = ""
        self.dropout_layer = ""


class CodeGenEngine(KnowledgeEngine):
    def __init__(self, builder: CodeBuilder):
        super().__init__()
        self.builder = builder

    # =========================================================================
    # OPTIMIZERS
    # =========================================================================
    @Rule(DatasetFact(dataset_size="small"))
    def opt_small(self):
        self.builder.optimizer_class = "Adam"
        self.builder.optimizer_extra = ""

    @Rule(DatasetFact(dataset_size="medium"))
    def opt_medium(self):
        self.builder.optimizer_class = "Adam"
        self.builder.optimizer_extra = ""

    @Rule(DatasetFact(dataset_size="large"))
    def opt_large(self):
        self.builder.optimizer_class = "SGD"
        self.builder.optimizer_extra = ", momentum=0.9"

    # =========================================================================
    # SCALING & OUTLIERS (PYTORCH)
    # =========================================================================
    @Rule(
        AND(
            FrameworkFact(name="pytorch"),
            FeatureFact(numerical_scale="different"),
            FeatureFact(numerical_outliers="no")
        )
    )
    def scale_pytorch_std(self):
        self.builder.scaler_import = "from sklearn.preprocessing import StandardScaler\n"
        self.builder.scaler_fit = (
            "scaler  = StandardScaler()\n"
            "X_scaled = scaler.fit_transform(X_train)\n"
            "X_val_sc = scaler.transform(X_val)\n"
        )

    @Rule(
        AND(
            FrameworkFact(name="pytorch"),
            FeatureFact(numerical_scale="different"),
            FeatureFact(numerical_outliers="yes")
        )
    )
    def scale_pytorch_robust(self):
        self.builder.scaler_import = "from sklearn.preprocessing import RobustScaler\n"
        self.builder.scaler_fit = (
            "# Outliers detected — using RobustScaler instead of StandardScaler\n"
            "scaler  = RobustScaler()\n"
            "X_scaled = scaler.fit_transform(X_train)\n"
            "X_val_sc = scaler.transform(X_val)\n"
        )

    # =========================================================================
    # SCALING & OUTLIERS (KERAS)
    # =========================================================================
    @Rule(
        AND(
            FrameworkFact(name="keras"),
            FeatureFact(numerical_scale="different"),
            FeatureFact(numerical_outliers="no")
        )
    )
    def scale_keras_std(self):
        self.builder.scaler_import = "from sklearn.preprocessing import StandardScaler\n"
        self.builder.scaler_fit = (
            "scaler   = StandardScaler()\n"
            "X_scaled = scaler.fit_transform(X_train)\n"
        )

    @Rule(
        AND(
            FrameworkFact(name="keras"),
            FeatureFact(numerical_scale="different"),
            FeatureFact(numerical_outliers="yes")
        )
    )
    def scale_keras_robust(self):
        self.builder.scaler_import = "from sklearn.preprocessing import RobustScaler\n"
        self.builder.scaler_fit = (
            "# Outliers detected — using RobustScaler instead of StandardScaler\n"
            "scaler   = RobustScaler()\n"
            "X_scaled = scaler.fit_transform(X_train)\n"
        )

    # =========================================================================
    # DROPOUT / OVERFITTING
    # =========================================================================
    @Rule(AND(FrameworkFact(name="pytorch"), TrainingFact(overfitting="yes")))
    def dropout_pytorch(self):
        self.builder.dropout_init = "        self.dropout = nn.Dropout(0.3)\n"
        self.builder.dropout_forward = "        x = self.dropout(x)\n"

    @Rule(AND(FrameworkFact(name="keras"), TrainingFact(overfitting="yes")))
    def dropout_keras(self):
        self.builder.dropout_layer = "    layers.Dropout(0.3),\n"

    # =========================================================================
    # PROBLEM TYPE & TARGETS (PYTORCH)
    # =========================================================================
    @Rule(AND(FrameworkFact(name="pytorch"), ProblemFact(target_kind="binary")))
    def target_pytorch_binary(self):
        self.builder.loss_function = "nn.BCELoss()"
        self.builder.output_activation = "        x = torch.sigmoid(x)\n"
        self.builder.output_size = "1"
        self.builder.label_dtype = "float32"
        self.builder.squeeze_pred = ".squeeze(-1)"

    @Rule(AND(FrameworkFact(name="pytorch"), ProblemFact(target_kind="multiclass")))
    def target_pytorch_multiclass(self):
        self.builder.loss_function = "nn.CrossEntropyLoss()"
        self.builder.output_activation = ""
        self.builder.output_size = "NUM_CLASSES"
        self.builder.label_dtype = "long"
        self.builder.squeeze_pred = ""

    @Rule(AND(FrameworkFact(name="pytorch"), ProblemFact(target_kind="continuous")))
    def target_pytorch_continuous(self):
        self.builder.loss_function = "nn.MSELoss()"
        self.builder.output_activation = ""
        self.builder.output_size = "1"
        self.builder.label_dtype = "float32"
        self.builder.squeeze_pred = ".squeeze(-1)"

    @Rule(AND(FrameworkFact(name="pytorch"), ProblemFact(target_kind="multilabel")))
    def target_pytorch_multilabel(self):
        self.builder.loss_function = "nn.BCELoss()"
        self.builder.output_activation = "        x = torch.sigmoid(x)\n"
        self.builder.output_size = "NUM_LABELS"
        self.builder.label_dtype = "float32"
        self.builder.squeeze_pred = ""

    # =========================================================================
    # PROBLEM TYPE & TARGETS (KERAS)
    # =========================================================================
    @Rule(AND(FrameworkFact(name="keras"), ProblemFact(target_kind="binary")))
    def target_keras_binary(self):
        self.builder.loss_function = "binary_crossentropy"
        self.builder.output_activation = "sigmoid"
        self.builder.output_size = "1"
        self.builder.metrics_list = '["accuracy"]'

    @Rule(AND(FrameworkFact(name="keras"), ProblemFact(target_kind="multiclass")))
    def target_keras_multiclass(self):
        self.builder.loss_function = "sparse_categorical_crossentropy"
        self.builder.output_activation = "softmax"
        self.builder.output_size = "NUM_CLASSES"
        self.builder.metrics_list = '["accuracy"]'

    @Rule(AND(FrameworkFact(name="keras"), ProblemFact(target_kind="continuous")))
    def target_keras_continuous(self):
        self.builder.loss_function = "mse"
        self.builder.output_activation = "linear"
        self.builder.output_size = "1"
        self.builder.metrics_list = '["mae"]'

    @Rule(AND(FrameworkFact(name="keras"), ProblemFact(target_kind="multilabel")))
    def target_keras_multilabel(self):
        self.builder.loss_function = "binary_crossentropy"
        self.builder.output_activation = "sigmoid"
        self.builder.output_size = "NUM_LABELS"
        self.builder.metrics_list = '["accuracy"]'


# =============================================================================
# Public Generator Dispatch
# =============================================================================

def generate_code(framework: str, params: dict) -> str:
    """
    Generate starter code using Experta rules.

    Args:
        framework : "pytorch" | "keras"
        params    : dict with questionnaire values

    Returns:
        A ready-to-run Python script as a string.
    """
    builder = CodeBuilder()
    engine = CodeGenEngine(builder)
    engine.reset()
    
    # Declare the facts derived from params
    engine.declare(FrameworkFact(name=framework))
    engine.declare(ProblemFact(target_kind=params.get("target_kind", "binary")))
    engine.declare(DatasetFact(dataset_size=params.get("dataset_size", "medium")))
    engine.declare(FeatureFact(
        numerical_scale=params.get("numerical_scale", "different"),
        numerical_outliers=params.get("numerical_outliers", "no")
    ))
    engine.declare(TrainingFact(overfitting=params.get("overfitting", "no")))
    
    engine.run()
    
    # Format templates based on the builder fields filled by the engine
    templates = {
        "pytorch": lambda: _PYTORCH_TEMPLATE.format(
            scaler_import    = builder.scaler_import,
            scaler_fit       = builder.scaler_fit,
            output_size      = builder.output_size,
            label_dtype      = builder.label_dtype,
            dropout_init     = builder.dropout_init,
            dropout_forward  = builder.dropout_forward,
            output_activation= builder.output_activation,
            loss_function    = builder.loss_function,
            optimizer_class  = builder.optimizer_class,
            optimizer_extra  = builder.optimizer_extra,
            squeeze_pred     = builder.squeeze_pred,
        ),
        "keras": lambda: _KERAS_TEMPLATE.format(
            scaler_import    = builder.scaler_import,
            scaler_fit       = builder.scaler_fit,
            output_size      = builder.output_size,
            dropout_layer    = builder.dropout_layer,
            output_activation= builder.output_activation,
            loss_function    = builder.loss_function,
            optimizer_class  = builder.optimizer_class,
            optimizer_extra  = builder.optimizer_extra,
            metrics_list     = builder.metrics_list,
        )
    }
    
    return templates[framework]()

